channels:
  - conda-forge
dependencies:
  - aiohttp>=3.10.2
  - botocore<1.36
  - configobj
  - netifaces
  - pip
  - pip:
    - posttroll==1.12.1
    - pytroll-collectors==0.17.0
  - python=3.12
  - pyyaml
  - pyzmq
  - s3fs>=2022.8.2
  - trollsift=0.5.3
  - urllib3>=2.2.2
  - zeromq
  - zipp>=3.19.1
